[api]
key = "xxxxxx"
api_url = "xxxxxx"
model_id = "gpt-4o-mini"
temperature = 0.1
parallel = 10
retry = 5
check_retry = 1
retry_delay = 1
time_out = 5

[download]
username = "xxxx"
max_version_count = 10
base_dir = "/xxx/xxx"
